version: '3.8'

services:
  hrv-mqtt-data:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hrv-mqtt-data
    hostname: hrv-mqtt-data
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    volumes:
      - .:/app

    network_mode: host  # Use the host's network stack directly
    privileged: true

    restart: unless-stopped

    # This passes the "--no-plot" argument to the script
    # command: ["python", "hrv-mqtt.py", "--no-plot"]

# networks:
#   hrv-mqtt-data-network:
#     driver: bridge
